### ISSUE TITLE
[feature/discussion] define a spec for generating a source URL for releases and scm versions, with variable expansion:

### ISSUE THREAD

**Issue by mrcjkb** [nvim-neorocks/lux#360]
suggestion: Perhaps we could define a spec for generating a source URL for releases and scm versions, with variable expansion:

```toml
[source.scm]
url = "git://github.com/nvim-neorocks/$(PACKAGE)"

[source.release]
url = "https://github.com/nvim-neorocks/$(PACKAGE)/archive/v$(VERSION).zip"
```

For building a local project, we replace the `SourceSpec` with one that points to the project root.

_Originally posted by @mrcjkb in https://github.com/nvim-neorocks/rocks/pull/325#discussion_r1917234556_
