### ISSUE TITLE
[Bug] Cannot build when `build.modules.<module>` is defined in `lux.toml`.

### ISSUE THREAD

**Issue by mbekkomo** [nvim-neorocks/lux#577]
```

thread 'main' panicked at lux-lib/src/project/project_toml.rs:642:14:
unable to convert local project to rockspec: MLua(SyntaxError { message: "[string \"lux-lib/src/lua_rockspec/mod.rs:102:13\"]:21: '}' expected (to close '{' at line 20) near '='", incomplete_input: false })
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: <lux_lib::project::project_toml::LocalProjectToml as lux_lib::hash::HasIntegrity>::hash
   4: lux_lib::build::do_build::{{closure}}
   5: lux_cli::build::build::{{closure}}
   6: lx::main::{{closure}}
   7: tokio::runtime::park::CachedParkThread::block_on
   8: tokio::runtime::context::runtime::enter_runtime
   9: tokio::runtime::runtime::Runtime::block_on
  10: lx::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Minimal repro:
1. `lx new lua-proj`
2. `cd lua-proj`
3. Modify `lux.toml`
```toml
package = "lua-proj"
version = "0.1.0"
lua = ">=5.1"

[description]
summary = ""
maintainer = "foo"
labels = [ "" ]

[run]
args = [ "src/main.lua" ]

[build]
type = "builtin"

[build.modules]
"foo.main" = "src/main.lua"

```
3. `lx build`
